language: rust
rust:
  - stable
compiler:
  - clang
env:
  - RUST_BACKTRACE=1 RUST_LOG=error
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - cargo cache -r registry
before_script:
  - rustup component add rustfmt clippy
  - (test -x $HOME/.cargo/bin/cargo-cache || cargo install cargo-cache)
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.2" mdbook)
  - cargo install-update -a
script:
  - cargo test --all-targets --no-run
  - cargo test --all
  - cargo test --examples
  - cargo fmt --all -- --check
  - cargo clippy --all-targets -- -D warnings
  - mdbook build libzmq-book
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: libzmq-book/book/
  keep-history: false
  on:
    branch: master
